Emoda.PekiYaBen.Web/Controllers/ContentController.cs
using Emoda.PekiYaBen.Business.DTOs;
using Emoda.PekiYaBen.Business.Queries;
using Emoda.PekiYaBen.Web.Models.DataTable;
using Emoda.PekiYaBen.Entity.Content;
using OLCA.Infrastructure.CQS;
using System;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using Emoda.PekiYaBen.Entity.Enums;
using Emoda.PekiYaBen.Business.Helpers;
using Emoda.PekiYaBen.Entity.Helpers;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.Data;
using Emoda.PekiYaBen.Business.Commands;
using Emoda.PekiYaBen.Entity.Coaching;
using Newtonsoft.Json;
using System.IO;

namespace Emoda.PekiYaBen.Web.Controllers
{
    [Authorize]
    public class ContentController : Controller
    {
        private IQueryDispatcher queryDispatcher;
        private ICommandDispatcher commandDispatcher;

        public ContentController(IQueryDispatcher queryDispatcher, ICommandDispatcher commandDispatcher)
        {
            this.queryDispatcher = queryDispatcher;
            this.commandDispatcher = commandDispatcher;
        }

        private string[] columns = new string[] {
            "Image",
            "Title",
            "Summary",
            "Category",
            "Status",
            "CreateDate"
        };

        public ActionResult Index(int id = 0)
        {
            ViewBag.Title = (General.ContentType)id + " Listesi";
            ViewBag.PageHeader = ViewBag.Title;
            ViewBag.ActivePage = "ContentList";

            return View(id);
        }

        public string GetContent(DataTableParameters dataParameter, int type)
        {
            GetContentListQuery query = new GetContentListQuery();
            query.Search = type.ToString();
            query.PageNumber = dataParameter.Start / dataParameter.Length + 1;
            query.PageSize = dataParameter.Length;

            StringBuilder sb = new StringBuilder();
            foreach (var order in dataParameter.Order)
            {
                sb.AppendFormat("{0} {1},", columns[order.Column], order.Dir);
            }
            int length = sb.Length;
            if (length > 0)
            {
                query.OrderBy = "ORDER BY " + sb.ToString().Substring(0, length - 1);
            }
            else
                query.OrderBy = "ORDER BY CreateDate desc";

            string json;
            try
            {
                var resultSet = new DataTableResultSet<ContentListItem>();
                var listResult = queryDispatcher.Dispatch<GetContentListQuery, QueryListResult<ContentListItem>>(query);
                resultSet.draw = dataParameter.Draw;
                resultSet.recordsTotal = listResult.Result.First().RecordCount;
                resultSet.recordsFiltered = resultSet.recordsTotal;
                resultSet.data = listResult.Result;
                //.Select(x => new ContentListItem
                //{
                //    Id = x.Id,
                //    CategoryId = x.CategoryId,
                //    Category = x.Category,
                //    Title = x.Title,
                //    Summary = x.Summary,
                //    Detail = x.Detail,
                //    Type = x.Type,
                //    CreateDate = x.CreateDate,
                //    Status = x.Status,
                //    Image = String.To
                //});

                json = resultSet.ToJSON();
            }
            catch (Exception ex)
            {
                DataTableResultError<ContentListItem> error = new DataTableResultError<ContentListItem>();
                error.error = "Bir hata oluştu. Lütfen sonra tekrar deneyiniz";
                json = error.ToJSON();
            }

            return json;
        }

        [HttpGet]
        public ActionResult Edit(int id = 0, int type = 0)
        {
            QuerySingleResult<ContentInfo> product = queryDispatcher.Dispatch<GetContentInfoQuery, QuerySingleResult<ContentInfo>>(new GetContentInfoQuery(id));
            var contentType = (product.Entity == null ? (General.ContentType)type : product.Entity.Type);
            ViewBag.Title = contentType + " Düzenle";
            ViewBag.PageHeader = ViewBag.Title;
            ViewBag.ActivePage = "ContentList";

            LoadPageMainLists(contentType);

            return View(product.Result);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(ContentInfo info, List<string> selectedObjects)
        {
            ContentInfo product;
            try
            {

                string productIds = String.Empty;
                if (selectedObjects != null)
                {
                    productIds = JsonConvert.SerializeObject(selectedObjects);
                }

                QuerySingleResult<ContentInfo> productQuery = queryDispatcher.Dispatch<GetContentInfoQuery, QuerySingleResult<ContentInfo>>(new GetContentInfoQuery(info.Id));
                product = (ContentInfo)productQuery.Result;

                var path = "";

                //C:\inetpub\wwwroot\pekiyaben.com\http\Content\assets\img\blog
                //C:\inetpub\wwwroot\pekiyaben.com\subdomains\yonetim\Content\

                path = Server.MapPath("/").Replace(@"subdomains\yonetim\", @"http\") + "content\\assets\\img\\blog\\" + info.Title.ToSEOFriendly(200) + ".png";

                ImageHelper.SaveImage(info.Image, path);

                var command = new UpdateContentCommand
                {
                    Id = info.Id,
                    Title = info.Title,
                    CategoryId = info.CategoryId,
                    CoachId = info.CoachId,
                    Type = info.Type,
                    Image = "/Content/assets/img/blog/" + info.Title.ToSEOFriendly(200) + ".png",
                    Summary = info.Summary,
                    Detail = info.Detail,
                    MetaDescription = info.MetaDescription,
                    MetaKeywords = info.MetaKeywords,
                    Status = info.Status,
                    ProductIds = productIds
                };

                product = (ContentInfo)commandDispatcher.Dispatch<UpdateContentCommand, ContentInfo>(command);

                LoadPageMainLists(info.Type);


            }
            catch (Exception ex)
            {
                return RedirectToAction("Edit", new { id = ex.Message });
            }
            return RedirectToAction("Edit", new { id = product.Id });
        }

        public void LoadPageMainLists(General.ContentType contentType)
        {
            DataAccess da = new DataAccess(System.Configuration.ConfigurationManager.ConnectionStrings["PekiYaBen"].ConnectionString);
            var categories = da.GetDataReader("Select Id, Title FROM ContentCategory WHERE Status=1 and Type=" + contentType.GetValue(), new List<SqlParameter> { });

            List<SelectListItem> categoryList = new List<SelectListItem>();
            foreach (DataRow row in categories.Rows)
            {
                SelectListItem item = new SelectListItem();
                item.Text = row["Title"].ToString();
                item.Value = row["Id"].ToString();
                categoryList.Add(item);
            }

            GetProductInfoListQuery query = new GetProductInfoListQuery();
            query.PageSize = 100;
            var products = queryDispatcher.Dispatch<GetProductInfoListQuery, QueryListResult<ProductInfo>>(query).Result;

            ViewBag.Products = products.Where(x => x.Type == Entity.Enums.General.ProductType.Meeting).ToList();

            ViewBag.Type = contentType;
            ViewBag.Categories = categoryList;

            var coaches = da.GetDataReader("Select Id, FullName FROM Coach Order By FullName ASC", new List<SqlParameter> { });

            List<SelectListItem> coachList = new List<SelectListItem>();
            foreach (DataRow row in coaches.Rows)
            {
                SelectListItem item = new SelectListItem();
                item.Text = row["FullName"].ToString();
                item.Value = row["Id"].ToString();
                coachList.Add(item);
            }

            ViewBag.Coaches = coachList;
        }

        public ActionResult Categories()
        {
            ViewBag.Title = "Kategori Listesi";
            ViewBag.PageHeader = ViewBag.Title;
            ViewBag.ActivePage = "ContentList";

            return View();
        }

        public string GetCategories(DataTableParameters dataParameter)
        {
            GetCategoryListQuery query = new GetCategoryListQuery();
            query.PageNumber = dataParameter.Start / dataParameter.Length + 1;
            query.PageSize = dataParameter.Length;
            query.OrderBy = "ORDER BY Type ASC, Title ASC";
            string json;
            try
            {
                var resultSet = new DataTableResultSet<CategoryListItem>();
                var listResult = queryDispatcher.Dispatch<GetCategoryListQuery, QueryListResult<CategoryListItem>>(query);
                resultSet.draw = dataParameter.Draw;
                resultSet.recordsTotal = listResult.Result.First().RecordCount;
                resultSet.recordsFiltered = resultSet.recordsTotal;
                resultSet.data = listResult.Result;

                json = resultSet.ToJSON();
            }
            catch (Exception ex)
            {
                DataTableResultError<ContentListItem> error = new DataTableResultError<ContentListItem>();
                error.error = "Bir hata oluştu. Lütfen sonra tekrar deneyiniz";
                json = error.ToJSON();
            }

            return json;
        }

        [HttpGet]
        public ActionResult EditCategory(int id = 0)
        {
            QuerySingleResult<ContentCategoryInfo> category = queryDispatcher.Dispatch<GetContentCategoryInfoQuery, QuerySingleResult<ContentCategoryInfo>>(new GetContentCategoryInfoQuery(id));
            ViewBag.Title = "Kategori Düzenle";
            ViewBag.PageHeader = ViewBag.Title;

Emoda.PekiYaBen.Web/Views/Content/Categories.cshtml
@using Emoda.PekiYaBen.Entity.Enums
@using Emoda.PekiYaBen.Entity.Helpers

@section styles{
    <link rel="stylesheet" type="text/css" href="~/Scripts/DataTables/datatables.min.css">
}
<div class="col-12">
    <a href="/Content/EditCategory" class="btn btn-danger btn-sm"><i class="glyphicon-plus"></i> Yeni Kategori Ekle</a><br /><br />
</div>
<table class="table table-striped" cellspacing="0" style="width: 100%" id="categories">
    <thead>
        <tr>
            <th>Başlık</th>
            <th>Tür</th>
            <th>Durum</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>
@section scripts {
    <script type="text/javascript">
        var statusList = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(EnumerationExtensions.ToList2<General.Status>()));
        var typeList = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(EnumerationExtensions.ToList2<General.ContentType>()));
        function FindInList(list, property, value) {
            var filtered = list.filter(function (list) { return eval("list." + property) == value });
            if (filtered)
                return filtered[0];
            else
                return null;
        }
    </script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/dt-1.10.21/b-1.6.2/cr-1.5.2/fc-3.3.1/fh-3.1.7/sc-2.0.2/sl-1.3.1/datatables.min.css" />
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.21/b-1.6.2/cr-1.5.2/fc-3.3.1/fh-3.1.7/sc-2.0.2/sl-1.3.1/datatables.min.js"></script>
    <script type="text/javascript">
        var table;
        $(function () {
            table = $('#categories').DataTable(
                {
                    scrollX: true,
                    responsive: true,
                    fixedHeader: true,
                    iDisplayLength: 100,
                    processing: true,
                    serverSide: true,
                    filter: false,
                    language: {
                        url: "/Scripts/DataTables/tr.json"
                    },
                    lengthMenu: [
                        [10, 25, 50, 100, 500, 1000],
                        [10, 25, 50, 100, 500, 1000]
                    ], //key-value
                    paging: true,
                    ordering: false,
                    info: true,
                    ajax: {
                        type: "POST",
                        contentType: "application/json",
                        url: '@Url.Action("GetCategories", "Content")',
                        data: function (d) {
                            return JSON.stringify(d);
                        },
                        dataFilter: function (res) {
                            return res;
                        },
                        error: function (x, y) {
                            console.log(x);
                        }
                    },
                    columns: [
                        {
                            data: "Title",
                            sType: "string",
                            render: function (data, type, full, meta) {
                                if (data !== "" && data !== null)
                                    return "<a href='/Content/EditCategory/" + full.Id + "'>" + data + "</a>";
                            }
                        },
                        {
                            data: "Type",
                            sType: "string",
                            render: function (data, type, full, meta) {
                                if (data !== "" && data !== null)
                                    return FindInList(typeList, "Key", data).Value;
                                return "";
                            }
                        },
                        {
                            data: "Status",
                            sType: "string",
                            render: function (data, type, full, meta) {
                                if (data !== "" && data !== null)
                                    return FindInList(statusList, "Key", data).Value;
                                return "";
                            }
                        }
                    ]
                });
        });
    </script>
}

Emoda.PekiYaBen.Web/Views/Content/EditCategory.cshtml
@using Emoda.PekiYaBen.Entity.Enums
@using Emoda.PekiYaBen.Entity.Content
@using Emoda.PekiYaBen.Entity.Helpers

@model ContentCategoryInfo

@section styles{

    <link href="~/Content/summernote/summernote-lite.min.css" rel="stylesheet" />
    <link href="~/Content/jquery.Jcrop.min.css" rel="stylesheet" />
    <style>
        #blah {
            background-color: #FFF;
            width: 825px;
            height: 500px;
            font-size: 24px;
            display: block;
        }
    </style>
}

<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            @using (Html.BeginForm("EditCategory", "Content", FormMethod.Post))
            {
                @Html.HiddenFor(m => m.Id)
            <div class="box-body">
                <div class="form-group col-sm-4">
                    <label for="Title">Başlığı</label>
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Title)
                </div>
                <div class="form-group col-sm-4">
                    <label for="Status">Türü</label>
                    @Html.EnumDropDownListFor(m => m.Type, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Type)
                </div>
                <div class="form-group col-sm-4">
                    <label for="Status">Durum</label>
                    @Html.EnumDropDownListFor(m => m.Status, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Status)
                </div>
            </div>
                <div class="box-footer text-right">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Kaydet</button>
                </div>
            }
        </div>
    </div>
</div>
@section scripts{
    @Html.Partial("_ValidationScriptsPartial");
}

Emoda.PekiYaBen.Web/Views/Content/Index.cshtml
@using Emoda.PekiYaBen.Entity.Enums
@using Emoda.PekiYaBen.Entity.Helpers
@model int

@section styles{
    <link rel="stylesheet" type="text/css" href="~/Scripts/DataTables/datatables.min.css">
}
<div class="col-12">
    <a href="/Content/Edit/?id=0&type=@Model" class="btn btn-danger btn-sm"><i class="glyphicon-plus"></i> Yeni @((General.ContentType)Model) Ekle</a><br /><br />
</div>
<table class="table table-striped" cellspacing="0" style="width: 100%" id="users">
    <thead>
        <tr>
            <th></th>
            <th>Başlık</th>
            <th>Özet</th>
            <th>Kategori</th>
            <th>Durum</th>
            <th>Eklenme Tarihi</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>
@section scripts {
    <script type="text/javascript">
        var statusList = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(EnumerationExtensions.ToList2<General.Status>()));
        var typeList = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(EnumerationExtensions.ToList2<General.ContentType>()));
        function FindInList(list, property, value) {
            var filtered = list.filter(function (list) { return eval("list." + property) == value });
            if (filtered)
                return filtered[0];
            else
                return null;
        }
    </script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/dt-1.10.21/b-1.6.2/cr-1.5.2/fc-3.3.1/fh-3.1.7/sc-2.0.2/sl-1.3.1/datatables.min.css" />
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.21/b-1.6.2/cr-1.5.2/fc-3.3.1/fh-3.1.7/sc-2.0.2/sl-1.3.1/datatables.min.js"></script>
    <script type="text/javascript">
        var table;
        $(function () {
            table = $('#users').DataTable(
                {
					scrollX: true,
					responsive: true,
                    fixedHeader: true,
                    iDisplayLength: 100,
                    processing: true,
                    serverSide: true,
                    filter:false,
                    language: {
                        url: "/Scripts/DataTables/tr.json"
                    },
                    lengthMenu: [
                        [10, 25, 50, 100, 500, 1000],
                        [10, 25, 50, 100, 500, 1000]
                    ], //key-value
                    paging: true,
                    ordering: true,
                    order: [[5, "desc"]],
                    info: true,
                    ajax: {
                        type: "POST",
                        contentType: "application/json",
                        url: '@Url.Action("GetContent", "Content")',
                        data: function (d) {
                            d.type=@Model;
                            return JSON.stringify(d);
                        },
                        dataFilter: function (res) {
                            return res;
                        },
                        error: function (x, y) {
                            console.log(x);
                        }
                    },
                    columns: [
                        {
                            "data": "Image",
                            "sType": "string",
                            sortable:false,
                            render: function (data, type, full, meta) {
                                if (data !== "" && data !== null)
                                    return "<img src='" + data + "' class='profile-user-img' />";

                                return "";
                            }
                        },
                        {
                            data: "Title",
                            sType: "string",
                            render: function (data, type, full, meta) {
                                if (data !== "" && data !== null)
                                    return "<a href='/Content/Edit/" + full.Id + "'>" + data + "</a>";
                            }
                        },
                        {
                            data: "Summary",
                            sType: "string",

                        },
                        {
                            data: "Category",
                            sType: "string",

                        },
                        {
                            data: "Status",
                            sType: "string",
                            render: function (data, type, full, meta) {
                                if (data !== "" && data !== null)
                                    return FindInList(statusList, "Key", data).Value;
                                return "";
                            }
                        },
                        {
                            "data": "CreateDate",
                            "sType": "date",
                            render: function (data, type, full, meta) {
                                if (data !== "" && data !== null && data != '01.01.0001')
                                    return moment(data).format('DD.MM.YYYY HH:mm');
                                return "";
                            }
                        }
                    ]
                });
        });
    </script>
}