Emoda.PekiYaBen.Web/Controllers/FAQController.cs
using Emoda.PekiYaBen.Business.Commands;
using Emoda.PekiYaBen.Business.DTOs;
using Emoda.PekiYaBen.Business.Queries;
using Emoda.PekiYaBen.Entity.FAQ;
using Emoda.PekiYaBen.Web.Models.DataTable;
using OLCA.Infrastructure.CQS;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Emoda.PekiYaBen.Web.Controllers
{
    [Authorize]
    public class FAQController : Controller
    {
        private IQueryDispatcher queryDispatcher;
        private ICommandDispatcher commandDispatcher;

        public FAQController(IQueryDispatcher queryDispatcher, ICommandDispatcher commandDispatcher)
        {
            this.queryDispatcher = queryDispatcher;
            this.commandDispatcher = commandDispatcher;
        }

        public ActionResult Index()
        {
            ViewBag.Title = "SSS Listesi";
            ViewBag.PageHeader = "SSS Listesi";
            ViewBag.ActivePage = "SSSList";

            return View();
        }

        public string GetFAQ(DataTableParameters dataParameter)
        {
            GetFAQListQuery query = new GetFAQListQuery();
            query.Search = dataParameter.Search.Value;

            string json;
            try
            {
                var resultSet = new DataTableResultSet<FAQListItem>();
                var listResult = queryDispatcher.Dispatch<GetFAQListQuery, QueryListResult<FAQListItem>>(query);
                resultSet.draw = dataParameter.Draw;
                resultSet.recordsTotal = listResult.Result.FirstOrDefault() != null ? listResult.Result.FirstOrDefault().RecordCount : 0;
                resultSet.recordsFiltered = resultSet.recordsTotal;
                resultSet.data = listResult.Result;

                json = resultSet.ToJSON();
            }
            catch (Exception ex)
            {
                DataTableResultError<FAQListItem> error = new DataTableResultError<FAQListItem>();
                error.error = "Bir hata oluştu. Lütfen sonra tekrar deneyiniz";
                json = error.ToJSON();
            }

            return json;
        }

        [HttpGet]
        public ActionResult Edit(int id = 0)
        {
            ViewBag.Title = "SSS Listesi";
            ViewBag.PageHeader = "SSS Listesi";
            ViewBag.ActivePage = "SSSList";

            QuerySingleResult<FAQInfo> product = queryDispatcher.Dispatch<GetFAQInfoQuery, QuerySingleResult<FAQInfo>>(new GetFAQInfoQuery(id));

            return View(product.Result);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(FAQInfo info)
        {
            ViewBag.Title = "SSS Listesi";
            ViewBag.PageHeader = "SSS Listesi";
            ViewBag.ActivePage = "SSSList";

            FAQInfo product;
            try
            {
                QuerySingleResult<FAQInfo> productQuery = queryDispatcher.Dispatch<GetFAQInfoQuery, QuerySingleResult<FAQInfo>>(new GetFAQInfoQuery(info.Id));
                product = (FAQInfo)productQuery.Result;

                var command = new UpdateFAQCommand
                {
                    Id = info.Id,
                    SortOrder = info.SortOrder,
                    Title = info.Title,
                    Description = info.Description,
                    Status = info.Status
                };
                product = (FAQInfo)commandDispatcher.Dispatch<UpdateFAQCommand, FAQInfo>(command);
            }
            catch (Exception ex)
            {
             
                return View();
            }

            return RedirectToAction("Edit", new { id = product.Id });
        }
    }
}

Emoda.PekiYaBen.Web/Views/FAQ/Edit.cshtml
@using Emoda.PekiYaBen.Entity.FAQ

@model FAQInfo

@section styles{
    <link href="~/Content/summernote/summernote-lite.min.css" rel="stylesheet" />
}
<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            @using (Html.BeginForm("Edit", "FAQ", FormMethod.Post))
            {
                @Html.HiddenFor(m => m.Id)
            <div class="box-body">
                <div class="form-group col-sm-4">
                    <label for="Title">Sıra No</label>
                    @Html.TextBoxFor(m => m.SortOrder, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.SortOrder)
                </div>
                <div class="form-group col-sm-8">
                    <label for="Status">Durum</label>
                    @Html.EnumDropDownListFor(m => m.Status, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Status)
                </div>
                <div class="form-group col-sm-12">
                    <label for="Title">SSS Başlık</label>
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control", @maxlength = "500" })
                    @Html.ValidationMessageFor(m => m.Title)
                </div>
                <div class="form-group col-sm-12">
                    <label for="Description">İçerik</label>
                    @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
                </div>
            </div>
                <div class="box-footer text-right">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Kaydet</button>
                </div>
            }
        </div>
    </div>
</div>
@section scripts{
    @Html.Partial("_ValidationScriptsPartial");
    <script src="~/Content/summernote/summernote-lite.js"></script>
    <script src="~/Content/summernote/lang/summernote-tr-TR.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#Description').summernote({
                lang: 'tr-TR',
                toolbar: [
                    ['style', ['bold', 'italic', 'underline', 'clear']],
                    ['font', ['strikethrough', 'fontsize']],
                    ['color', ['color', 'forecolor']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['insert', ['height']],
                    ['link', ['link']],
                    ['picture', ['picture']]
                ],
                height: 300
            });
        });
    </script>
}

Emoda.PekiYaBen.Web/Views/FAQ/Index.cshtml
@using Emoda.PekiYaBen.Entity.Enums
@using Emoda.PekiYaBen.Entity.Helpers

@section styles{
    <link rel="stylesheet" type="text/css" href="~/Scripts/DataTables/datatables.min.css">
}
<div class="col-12">
    <a href="/FAQ/Edit/" class="btn btn-danger btn-sm"><i class="glyphicon-plus"></i> Yeni SSS Ekle</a><br /><br />
</div>
<table class="table table-striped" cellspacing="0" style="width: 100%" id="users">
    <thead>
        <tr>
            <th>Sıra No</th>
            <th>Başlık</th>
            <th>Tarih</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>
@section scripts {
    <script type="text/javascript">
        function FindInList(list, property, value) {
            var filtered = list.filter(function (list) { return eval("list." + property) == value });
            if (filtered)
                return filtered[0];
            else
                return null;
        }
    </script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/dt-1.10.21/b-1.6.2/cr-1.5.2/fc-3.3.1/fh-3.1.7/sc-2.0.2/sl-1.3.1/datatables.min.css" />
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.21/b-1.6.2/cr-1.5.2/fc-3.3.1/fh-3.1.7/sc-2.0.2/sl-1.3.1/datatables.min.js"></script>
    <script type="text/javascript">
        var table;
        $(function () {
            table = $('#users').DataTable(
                {
					scrollX: true,
					responsive: true,
                    fixedHeader: true,
                    iDisplayLength: 100,
                    processing: true,
                    serverSide: true,
                    filter:false,
                    language: {
                        url: "/Scripts/DataTables/tr.json"
                    },
                    lengthMenu: [
                        [10, 25, 50, 100, 500, 1000],
                        [10, 25, 50, 100, 500, 1000]
                    ], //key-value
                    paging: false,
                    ordering: false,
                    order: [[1, "asc"], [2,"asc"]],
                    info: true,
                    ajax: {
                        type: "POST",
                        contentType: "application/json",
                        url: '@Url.Action("GetFAQ", "FAQ")',
                        data: function (d) {
                            return JSON.stringify(d);
                        },
                        dataFilter: function (res) {
                            return res;
                        },
                        error: function (x, y) {
                            debugger;
                            console.log(x);

                        }
                    },
                    columns: [
                        {
                            data: "SortOrder",
                            sType: "int",

                        },
                        {
                            data: "Title",
                            sType: "string",
                            render: function (data, type, full, meta) {
                                if (data !== "" && data !== null)
                                    return "<a href='/FAQ/Edit/" + full.Id + "'>" + data + "</a>";
                            }

                        },
                        {
                            "data": "CreatedDate",
                            "sType": "date",
                            render: function (data, type, full, meta) {
                                if (data !== "" && data !== null && data != '01.01.0001')
                                    return moment(data).format('DD.MM.YYYY');
                                return "";
                            }
                        }

                    ]
                });
        });
    </script>
}